name: Conditional Pipeline Builder
description: developing
author: https://github.com/a-github-user
requirements: []
configuration:
  properties:
    conditional-pipeline-slug:
      type: string
    # TODO: docs are nonexistent for how to get the BUILDKIT_PLUGIN_* input variable names for an array or object, using string for now
    # https://buildkite.com/docs/plugins/writing
    # lint-group:
    #   type: [array]
    #   properties:
    #     key: 
    #       type: string
    #     includes:
    #       type: string
    lint-group: 
      type: array
  additionalProperties: false
