name: Conditional Pipeline Builder
description: developing
author: https://github.com/a-github-user
requirements: []
configuration:
  properties:
    conditional-pipeline-slug:
      type: string
    lint-group:
      type: [array]
      properties:
        key: 
          type: string
        includes:
          type: string
  additionalProperties: false
